// +build !ignore_autogenerated

/*
Copyright 2021 Rainbow Project.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticityStrategyKind) DeepCopyInto(out *ElasticityStrategyKind) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticityStrategyKind.
func (in *ElasticityStrategyKind) DeepCopy() *ElasticityStrategyKind {
	if in == nil {
		return nil
	}
	out := new(ElasticityStrategyKind)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SloMapping) DeepCopyInto(out *SloMapping) {
	*out = *in
	out.TargetRef = in.TargetRef
	out.ElasticityStrategy = in.ElasticityStrategy
	if in.StabilizationWindow != nil {
		in, out := &in.StabilizationWindow, &out.StabilizationWindow
		*out = new(StabilizationWindow)
		(*in).DeepCopyInto(*out)
	}
	if in.StaticElasticityStrategyConfig != nil {
		in, out := &in.StaticElasticityStrategyConfig, &out.StaticElasticityStrategyConfig
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SloMapping.
func (in *SloMapping) DeepCopy() *SloMapping {
	if in == nil {
		return nil
	}
	out := new(SloMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SloTarget) DeepCopyInto(out *SloTarget) {
	*out = *in
	out.CrossVersionObjectReference = in.CrossVersionObjectReference
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SloTarget.
func (in *SloTarget) DeepCopy() *SloTarget {
	if in == nil {
		return nil
	}
	out := new(SloTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StabilizationWindow) DeepCopyInto(out *StabilizationWindow) {
	*out = *in
	if in.ScaleUpSeconds != nil {
		in, out := &in.ScaleUpSeconds, &out.ScaleUpSeconds
		*out = new(int32)
		**out = **in
	}
	if in.ScaleDownSeconds != nil {
		in, out := &in.ScaleDownSeconds, &out.ScaleDownSeconds
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StabilizationWindow.
func (in *StabilizationWindow) DeepCopy() *StabilizationWindow {
	if in == nil {
		return nil
	}
	out := new(StabilizationWindow)
	in.DeepCopyInto(out)
	return out
}
