package kubeutil

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

const (
	// Name of the label that identifies a pod as generated by the service graph controller.
	LabelRainbowGeneratedPod = "rainbow-h2020.eu/generated-pod-label"

	// Name of the label to reference a service graph resource in the same namespace.
	LabelRefServiceGraph = "rainbow-h2020.eu/service-graph"

	// Name of the label to reference a node in a service graph.
	LabelRefServiceGraphNode = "rainbow-h2020.eu/service-graph-node"
)

// GetLabel returns the label with the specified key.
func GetLabel(obj *metav1.ObjectMeta, key string) (string, bool) {
	if obj.Labels != nil {
		value, exists := obj.Labels[key]
		return value, exists
	}
	return "", false
}

// GetNamespace returns the namespace of the object, or "default" if the namespace is not set.
func GetNamespace(obj *metav1.ObjectMeta) string {
	if obj.Namespace != "" {
		return obj.Namespace
	}
	return "default"
}
