package kubeutil

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

const (
	// Name of the label that identifies a pod as generated by the service graph controller.
	LabelRainbowGeneratedPod = "rainbow-h2020.eu/generated-pod-label"

	// Name of the label to reference a service graph resource in the same namespace.
	LabelRefServiceGraph = "rainbow-h2020.eu/service-graph"

	// Name of the label to reference a node in a service graph.
	LabelRefServiceGraphNode = "rainbow-h2020.eu/service-graph-node"

	// Name of the annotation that stores the resourceVersion of the service graph, from which an object was last updated.
	AnnotationLastUpdatedByServiceGraphVersion = "rainbow-h2020.eu/last-updated-by-service-graph-version"

	// Name of the annotation that stores the hash of the spec that was used for creating an object.
	// See SetSpecHash()
	AnnotationSpecHash = "rainbow-h2020.eu/spec-hash"
)

// GetLabel returns the label with the specified key.
func GetLabel(obj metav1.Object, key string) (string, bool) {
	if labels := obj.GetLabels(); labels != nil {
		value, exists := labels[key]
		return value, exists
	}
	return "", false
}

// GetNamespace returns the namespace of the object, or "default" if the namespace is not set.
func GetNamespace(obj metav1.Object) string {
	if namespace := obj.GetNamespace(); namespace != "" {
		return namespace
	}
	return "default"
}

// GetAnnotation returns the annotation with the specified key.
func GetAnnotation(obj metav1.Object, key string) (string, bool) {
	if annotations := obj.GetAnnotations(); annotations != nil {
		value, exists := annotations[key]
		return value, exists
	}
	return "", false
}

// SetAnnotation sets the annotation indicated by the key to the specified value.
func SetAnnotation(obj metav1.Object, key, value string) {
	annotations := obj.GetAnnotations()
	if annotations == nil {
		annotations = make(map[string]string)
		obj.SetAnnotations(annotations)
	}
	annotations[key] = value
}
